" vint: -ProhibitSetNoCompatible

let s:plugin_root = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')

if exists('$PRETTIER_EXEC_CMD_PATH') && $PRETTIER_EXEC_CMD_PATH !=# ''
    let g:prettier#exec_cmd_path = $PRETTIER_EXEC_CMD_PATH
endif

if filereadable('/rtp.vim')
    source /rtp.vim
endif

" Load builtin plugins
" We need this because run_vim.sh sets -i NONE
if has('win32')
    execute 'set runtimepath=$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,C:\vader,' . fnameescape(s:plugin_root)
else
    execute 'set runtimepath=/home/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,' . fnameescape(s:plugin_root) . ',/vader'
endif

" The following is just an example
filetype plugin indent on
syntax on

if !has('win32')
    set shell=/bin/sh
    set shellcmdflag=-c
endif

set nocompatible
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
autocmd FileType graphql setlocal shiftwidth=4 tabstop=4 softtabstop=4
set backspace=2
set nofoldenable
set foldmethod=syntax
set foldlevelstart=10
set foldnestmax=10
set ttimeoutlen=0

" The encoding must be explicitly set for tests for Windows.
execute 'set encoding=utf-8'
